---
title: "eConsent Training Tracking"
author: "JP Giliberto MD"
format: dashboard

---

```{r}
library(tidyverse)
library (lubridate)
library(gt)
library(scales)
library(rjson)
library(readxl)
library(ggsurvfit)
library(survival)

Provider_Training_Distribution <- read_excel("Provider Training Distribution.xlsx")
filenamescon <- list.files("C:/Users/jpgil/OneDrive/Documents/R/eConsent/exports", pattern="*.xlsx", full.names=TRUE)
completed<- read_excel(filenamescon)

training_data <- Provider_Training_Distribution |> 
  left_join(completed) |> 
  mutate(Completed = !is.na(ID))


 # this should give you a character vector, with each file name represented by an entry
```

# Completion Rates

## Row - Badges {height=20%}

```{r}
#| content: valuebox
#| title: "Total Completion Rate"

total_rate <- training_data |> 
  summarise(Total_Completion_Rate = round(sum(Completed)/n(), 3))
list(icon = "bookmark-check-fill",
     color = "success",
     value = percent(pull(total_rate,1),accuracy = 0.1)
)
```

```{r} 
#| content: valuebox
#| title: "Last Updated"

Update <- training_data |> 
  summarise(last_update = format(max(`Completion time`, na.rm = T),"%m/%d")) 

numby =pull(Update,1)

list(
  icon = "calendar",
  color = "primary",
  value = numby
)

```

## Row - Completion Rates by Specialty {height = 80%}

```{r}
#|title: "Total Completion Rate by Specialty"

completion_rates <- training_data |> 
  group_by(Department) |> 
  summarise(Completed = round(sum(Completed)/n(), 3))

ggplot(completion_rates, aes(x = reorder(Department, Completed),
                             y = Completed, 
                             label = percent(Completed, accuracy = 0.1), 
                             color = Completed, 
                             fill=Completed)) +
  geom_col() +
  geom_text(nudge_y = 0.04, color = "black")+
  scale_color_continuous(type = "viridis")+
  scale_fill_continuous(type = "viridis")+
  coord_flip()+
  xlab("Specialty")+
  ylab("Percent Completed")+
  theme_bw(base_size = 14)

```

```{r}

data_surv <- training_data |>
  mutate(`Completion time2`= if_else(is.na(`Completion time`),now(),`Completion time`)) |> 
  mutate(days_to_complete = difftime(`Completion time2`, ymd_hms("2025-05-29 00:00:01", tz = "UTC"), units = "days"))


R_surv <- Surv(time = data_surv$days_to_complete, event = data_surv$Completed)
R_surv_fit <- survfit(R_surv ~ 1, data=data_surv)
ggsurvfit(R_surv_fit, type= "risk", linewidth = 1.75, color="purple3")+
  geom_vline(xintercept = 33,linewidth = 2, linetype = "dashed", color = "gold")+
  geom_vline(xintercept = 40, linewidth = 2, linetype = "dashed", color = "red")+
  annotate("text", x = 10, y = 0.5, label = "Orange = July 1st | Red = July 8th, past due")+
  scale_y_continuous(expand = c(0.025, 0), limits = c(0, 1),n.breaks = 10, label = scales::label_percent())+
  scale_x_continuous(expand = c(0.015, 0), limits = c(0, 40),n.breaks = 8)+
  xlab("Days Since Training Email")+
  ylab("Completion Rate")

```

# Comments

```{r}
comment_list <- training_data |> 
  select(Email, questions = `Questions about eConsent process:`) |> 
  filter(!is.na(questions))

no_comments <- comment_list |> 
  mutate(Question = str_to_sentence(questions)) |> 
   mutate(No_Qs = str_starts(Question,"N") & str_length(Question) <50) |> 
  filter(No_Qs ==T)

```

## Row - Badges {height=20%}

```{r}
#| content: valuebox
#| title: "Number of No/None Q"

total_no_comm <- no_comments |> 
  summarise(Number = sum(No_Qs))

list(icon = "ban",
     color = "danger",
     value = pull (total_no_comm,1)
)
```

```{r} 
#| content: valuebox
#| title: "Last Updated"

total_other_comm <- comment_list |>
  mutate(Question = str_to_sentence(questions)) |> 
  mutate(No_Qs = str_starts(Question,"N") & str_length(Question) <50) |> 
  filter(No_Qs ==F) |> 
  summarise(Number = n())

list(icon = "card-checklist",
     color = "success",
     value = pull (total_other_comm,1))


```

## Row - Comment details {height=80%}

### Details of No/None Q
```{r}

total_no_comm_details <- no_comments |> 
  group_by(Question) |> 
  count() 

total_no_comm_details <- as.data.frame(total_no_comm_details)

total_no_comm_details |> 
  rename(Response = Question)|> 
  gt()
```
### Details of Questions {.tabset}

```{r}
#| title: "All Comments"

comm_details <- comment_list |> 
  mutate(Question = str_to_sentence(questions)) |> 
  mutate(No_Qs = str_starts(Question,"N") & str_length(Question) <50) |> 
  filter(No_Qs ==F) |> 
  left_join(training_data) |>
  select(Name, Email, Question) |> 
  gt()

comm_details
  
```
```{r}
#| title: "Pending"

Responded_To <- c("clb46@uw.edu","calhounk@uw.edu", "schiang@uw.edu","sinadada@uw.edu","tbdodson@uw.edu", "rge@uw.edu", "ellint@uw.edu", "bgoff@uw.edu", 	"jihuang@uw.edu", "karik3@uw.edu", "meyertk@uw.edu", "krismoe@uw.edu", 	"lowens2@uw.edu", "chrismp@uw.edu", "scriba@uw.edu", "ashope@uw.edu","elisej@uw.edu", "lazeck@uw.edu", "bshaffer@uw.edu", "jlm@uw.edu","katmo@uw.edu" )

comm_details_JPG_todo <- comment_list |> 
  mutate(Question = str_to_sentence(questions)) |> 
  mutate(No_Qs = str_starts(Question,"N") & str_length(Question) <50) |> 
  filter(No_Qs ==F) |> 
  left_join(training_data) |> 
  mutate(JPG_to_respond = (!Email%in%Responded_To)) |> 
  filter(JPG_to_respond) |> 
  select(Name, Email, Question) |> 
  gt()

comm_details_JPG_todo
  
```

# Emails

## Row - Emails

```{r}
non_responders <- training_data |> 
  filter(!Completed) |> 
  group_by(`Provider Type`) |> 
  summarise(Count = n(),
    Email_list = str_flatten (Email, collapse = "; ")) |> 
  gt()

non_responders
```

# Chair List

## Row - Emails {.tabset}

```{r}
#| label: Goff
#| title: Goff
chair = "Barbara Goff"
non_responder_chair <- training_data |> 
  filter(!Completed &
           Chair == chair) |> 
  group_by(`Provider Type`) |>
  mutate(full_name = str_c(`First Name`,`Last Name`, sep = " " )) |> 
  summarise(Count = n(),
            Surgeon_list = str_flatten (full_name, collapse = " | "),
            Email_list = str_flatten (Email, collapse = "; ")
            ) |> 
  gt()

non_responder_chair
```

```{r}
#| label: Ellenbogen
#| title: Ellenbogen
chair = "Richard Ellenbogen"
non_responder_chair <- training_data |> 
  filter(!Completed &
           Chair == chair) |> 
  group_by(`Provider Type`) |>
  mutate(full_name = str_c(`First Name`,`Last Name`, sep = " " )) |> 
  summarise(Count = n(),
            Surgeon_list = str_flatten (full_name, collapse = " | "),
            Email_list = str_flatten (Email, collapse = "; ")
            ) |> 
  gt()

non_responder_chair
```

```{r}
#| label: Futran
#| title: Futran
chair = "Neal Futran"
non_responder_chair <- training_data |> 
  filter(!Completed &
           Chair == chair) |> 
  group_by(`Provider Type`) |>
  mutate(full_name = str_c(`First Name`,`Last Name`, sep = " " )) |> 
  summarise(Count = n(),
            Surgeon_list = str_flatten (full_name, collapse = " | "),
            Email_list = str_flatten (Email, collapse = "; ")
            ) |> 
  gt()

non_responder_chair
```


```{r}
#| label: Wood
#| title: Wood
chair = "Doug Wood"
non_responder_chair <- training_data |> 
  filter(!Completed &
           Chair == chair) |> 
  group_by(`Provider Type`) |>
  mutate(full_name = str_c(`First Name`,`Last Name`, sep = " " )) |> 
  summarise(Count = n(),
            Surgeon_list = str_flatten (full_name, collapse = " | "),
            Email_list = str_flatten (Email, collapse = "; ")
            ) |> 
  gt()

non_responder_chair
```



```{r}
#| label: Rezaei
#| title: Rezaei
chair = "Kasra Rezaei"
non_responder_chair <- training_data |> 
  filter(!Completed &
           Chair == chair) |> 
  group_by(`Provider Type`) |>
  mutate(full_name = str_c(`First Name`,`Last Name`, sep = " " )) |> 
  summarise(Count = n(),
            Surgeon_list = str_flatten (full_name, collapse = " | "),
            Email_list = str_flatten (Email, collapse = "; ")
            ) |> 
  gt()

non_responder_chair
```


```{r}
#| label: Lin
#| title: Lin
chair = "Dan Lin"
non_responder_chair <- training_data |> 
  filter(!Completed &
           Chair == chair) |> 
  group_by(`Provider Type`) |>
  mutate(full_name = str_c(`First Name`,`Last Name`, sep = " " )) |> 
  summarise(Count = n(),
            Surgeon_list = str_flatten (full_name, collapse = " | "),
            Email_list = str_flatten (Email, collapse = "; ")
            ) |> 
  gt()

non_responder_chair
```

```{r}
#| label: Chansky
#| title: Chansky
chair = "Howard Chansky"
non_responder_chair <- training_data |> 
  filter(!Completed &
           Chair == chair) |> 
  group_by(`Provider Type`) |>
  mutate(full_name = str_c(`First Name`,`Last Name`, sep = " " )) |> 
  summarise(Count = n(),
            Surgeon_list = str_flatten (full_name, collapse = " | "),
            Email_list = str_flatten (Email, collapse = "; ")
            ) |> 
  gt()

non_responder_chair
```

```{r}
#| label: Dodson
#| title: Dodson
chair = "Thomas Dodson"
non_responder_chair <- training_data |> 
  filter(!Completed &
           Chair == chair) |> 
  group_by(`Provider Type`) |>
  mutate(full_name = str_c(`First Name`,`Last Name`, sep = " " )) |> 
  summarise(Count = n(),
            Surgeon_list = str_flatten (full_name, collapse = " | "),
            Email_list = str_flatten (Email, collapse = "; ")
            ) |> 
  gt()

non_responder_chair
```